agents:
  - name: DataFetcherAgent
    module: agents.data_fetcher_agent
    class: DataFetcherAgent

  - name: GPT4QueryAgent
    module: agents.gpt4_query_agent
    class: GPT4QueryAgent

  - name: ResultValidatorAgent
    module: agents.result_validator_agent
    class: ResultValidatorAgent
